development:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: ejemplos_development
  pool: 5
  username: root
  password: tm2001mm
  socket: /var/run/mysqld/mysqld.sock

test:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: ejemplos_test
  pool: 5
  username: root
  password: tm2001mm
  socket: /var/run/mysqld/mysqld.sock

production:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: ejemplos_production
  pool: 5
  username: root
  password: tm2001mm
  socket: /var/run/mysqld/mysqld.sock

